[package]
name = "rust-microservice"
version = "0.1.0"
authors = ["Oscar Buck <33234035+0xBlockchain@users.noreply.github.com>"]
edition = "2018"

[dependencies]
hyper = "0.12"
futures = "0.1"
slab = "0.4"
lazy_static = "1.0"
regex = "1.0"
